version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/
    resource_class: large
    environment:
      R_LIBS: /home/circleci/Rlibs
      ExternalData_OBJECT_STORES: /home/circleci/.ExternalData
    steps:
      - checkout:
          path : ~/SimpleITKRInstaller
      - run:
          name: System Dependencies
          command: |
            sudo apt-get -y install software-properties-common apt-transport-https
            sudo add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/debian jessie-cran34/"
            sudo apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
            sudo apt-get update
            sudo apt-get -y install r-base-dev rsync
            mkdir ~/Rlibs
            sudo pip install numpy scikit-ci-addons
            ci_addons circle/install_cmake.py 3.7.2
      - run:
          name: Install R Package Dependencies
          command: |
             R -e 'install.packages("devtools", repo="http://cloud.r-project.org/")'
      - run:
          name: Build SimpleITK R Package
          no_output_timeout: 20.0m
          environment:
             MAKEJ: 3
             RTESTON: ON
             ITK_GLOBAL_DEFAULT_NUMBER_OF_THREAD: 2
          command: |
             R -e "devtools::install(c('/home/circleci/SimpleITKRInstaller'), args=c('--configure-vars="MAKEJ=3"'))"
      - run:
          name: Test SimpleITK R Package
          no_output_timeout: 20.0m
          working_directory: ~/SimpleITKRInstaller/SITK/Build/SimpleITK-build/
          environment:
             ITK_GLOBAL_DEFAULT_NUMBER_OF_THREAD: 2
             PARALLEL_LEVEL: 4
             CTEST_OUTPUT_ON_FAILURE: 1
          command: |
             ctest -V

